# name: 'Release'
name: '🏷️  '
description: 'Localized Release'
author: 'JeromeFitz'

inputs:
  GH_TOKEN:
    descirption: 'Github Personal Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: '🐙️  Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
    - name: '🏷️  Release'
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        yarn semantic-release
