# name: 'Release'
name: '🏷️  '
description: 'Localized Release'
author: 'JeromeFitz'

inputs:
  GH_TOKEN:
    descirption: 'Provide GitHub Token'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: '🏷️  Release'
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        yarn semantic-release
