const CONTENT_NODE_TYPES = {
  OL: 'ol',
  UL: 'ul',
  UNSUPPORTED: '_unsupported',
  //
  BULLETED_LIST_ITEM: 'bulleted_list_item',
  BULLETED_LIST: 'bulleted_list',
  CALLOUT: 'callout',
  CHECKBOX: 'checkbox',
  CODE: 'code',
  COLUMN_LIST: 'column_list',
  COLUMN: 'column',
  DATE: 'date',
  DIVIDER: 'divider',
  FILES: 'files',
  HEADING_1: 'heading_1',
  HEADING_2: 'heading_2',
  HEADING_3: 'heading_3',
  IMAGE: 'image',
  LINK: 'link',
  MULTI_SELECT: 'multi_select',
  NUMBERED_LIST_ITEM: 'numbered_list_item',
  NUMBERED_LIST: 'numbered_list',
  PARAGRAPH: 'paragraph',
  QUOTE: 'quote',
  RELATION: 'relation',
  RICH_TEXT: 'rich_text',
  TITLE: 'title',
  TO_DO: 'to_do',
  TOGGLE: 'toggle',
  URL: 'url',
}

export { CONTENT_NODE_TYPES }
