# name: 'Init And Lint'
name: '💽️  ➕️  🚨️  '
description: 'Localized Init And Lint'
author: 'JeromeFitz'

inputs:
  TURBO_TEAM:
    description: 'Provide Team ID for Turbo'
    required: true
    type: string
  TURBO_TOKEN:
    description: 'Provide Token for Turbo'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: '🐙️  Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: '💽️  Node (16)'
      id: node-setup
      uses: actions/setup-node@v2
      with:
        # architecture: 'x64'
        cache-dependency-path: yarn.lock
        cache: 'yarn'
        node-version: '16'

    - name: '📦️  Dependencies'
      id: dependencies
      shell: bash
      run: |
        yarn install --frozen-lockfile --ignore-engines --network-concurrency 1

    - name: '🔺️  Cache (turbo)'
      id: cache-turbo
      uses: actions/cache@v2
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      with:
        path: .cache-turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        # order of preference => turbo will re-check
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-
          turbo-${{ github.job }}-
          turbo-

    - name: '🚨️  Lint'
      id: lint
      shell: bash
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      run: |
        yarn lint --cache-dir=".cache-turbo"

    - name: '🧪️  Test'
      id: test
      shell: bash
      # @note(ci) comment out right now as this requires `build`
      run: |
        echo # yarn test --cache-dir=".cache-turbo"
