# name: 'Lint'
name: '🚨️  '
description: 'Localized Lint'
author: 'JeromeFitz'

inputs:
  TURBO_TEAM:
    description: 'Provide Team ID for Turbo'
    required: true
    type: string
  TURBO_TOKEN:
    description: 'Provide Token for Turbo'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    # @todo(gh-actions) Separate `main` from PR
    - name: '🎨  Format'
      id: format
      shell: bash
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      run: |
        pnpm run format:prettier:check

    # @todo(gh-actions) Separate `main` from PR
    - name: '🚨️  Lint'
      id: lint
      shell: bash
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      run: |
        TURBO_TELEMETRY_DISABLED=1 pnpm turbo run lint --cache-dir=".cache-turbo"
