# name: 'Lint'
name: '🚨️  '
description: 'Localized Lint'
author: 'JeromeFitz'

inputs:
  TURBO_TEAM:
    description: 'Provide Team ID for Turbo'
    required: true
    type: string
  TURBO_TOKEN:
    description: 'Provide Token for Turbo'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: '🚨️  Lint'
      id: lint
      shell: bash
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      run: |
        pnpm turbo run lint --cache-dir=".cache-turbo" --continue

    # - name: '🧪️  Test'
    #   id: test
    #   shell: bash
    #   # @note(ci) comment out right now as this requires `build`
    #   run: |
    #     echo # pnpm test --cache-dir=".cache-turbo"
