#!/bin/sh

[ -n "$CI" ] && exit 0

pnpm run format:prettier --staged
exec < /dev/tty
# @note(git-cz) publish w/ this
pnpm git-cz --hook || true
# @note(git-cz) pnpm link w/ this
# node ./node_modules/@jeromefitz/git-cz/dist/cli.js --hook || true
