# name: 'Init'
name: '💽️  '
description: 'Localized Init'
author: 'JeromeFitz'

inputs:
  node-version:
    description: 'Node version'
    required: true
    default: '18'
  pnpm-version:
    description: 'pnpm version'
    required: true
    default: '8'

runs:
  using: 'composite'
  steps:
    - name: '🔧  pnpm'
      id: pnpm-setup
      uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: '💽️  Node ${{ inputs.node-version }}'
      id: node-setup
      uses: actions/setup-node@v3
      with:
        # architecture: 'x64'
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version: ${{ inputs.node-version }}

    # @todo(actions) may not need to install these _every_ time
    - name: '🎭  Playwright'
      id: playwright-setup
      shell: bash
      run: pnpm playwright install --with-deps

    - name: '💡  Lighthouse'
      id: lighthouse-setup
      shell: bash
      run: pnpm add @lhci/cli -g
