# name: 'Init'
name: '💽️  '
description: 'Localized Init'
author: 'JeromeFitz'

inputs:
  node-version:
    default: '20'
    description: '🔢  Node version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: '🔧  pnpm: Get Corepack Version'
      id: node-pnpm-version
      shell: bash
      run: echo PNPM_VERSION=$(node --print 'require("./package.json").packageManager') >> $GITHUB_ENV

    - name: '🔧  pnpm: Install'
      id: pnpm-setup
      shell: bash
      # @note(corepack) Why, that was quite the rabbit hole
      #  on corepack|npm and github actions ... yikes.
      #
      # How about you just install it and do not use corepack for now.
      # :homer-simpson-fade-backwards-into-bushes:
      #
      run: |
        npm install -g ${{ env.PNPM_VERSION }}

      # uses: pnpm/action-setup@v2.4.0
      # with:
      #   version: ${{ inputs.pnpm-version }}

    - name: '💽️  Node ${{ inputs.node-version }}'
      id: node-setup
      uses: actions/setup-node@v4
      with:
        # architecture: 'x64'
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version: ${{ inputs.node-version }}
