# name: 'Init And Lint'
name: '💽️  '
description: 'Localized Init'
author: 'JeromeFitz'

runs:
  using: 'composite'
  steps:
    - name: '🔧  pnpm'
      id: pnpm-setup
      uses: pnpm/action-setup@v2
      with:
        version: 7.3.0

    - name: '💽️  Node'
      id: node-setup
      uses: actions/setup-node@v2
      with:
        # architecture: 'x64'
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version: 16

    - name: '📦️  Dependencies'
      id: dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
