name: '🚀️  '

on:
  workflow_call:
    inputs:
      PRODUCTION:
        required: true
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_TOKEN:
        required: true

jobs:
  deploy:
    name: '🚀️  '
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: '🐙️  Checkout'
        id: wf-checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: '🔺️ Deploy'
        id: wf-deploy
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          CREATE_COMMENT: true
          DELETE_EXISTING_COMMENT: true
          PR_LABELS: false
          PRODUCTION: ${{ inputs.PRODUCTION }}
